### ISSUE TITLE
Allow exclusion of URL's from crawler

### ISSUE THREAD

**Issue by tohmjudson-ms** [microsoft/accessibility-insights-action#1019]
### Problem
When using the Accessibility Insights Azure DevOps Task, the pipeline allows for the use of discovery patterns. However, this appears to be limited to adding URL and not excluding them.

### Ask
I would like to see an additional parameter to exclude URLs via regex (or other options) in the same manner as the discovery pattern

### Examples: 
Exclude url’s that include query parameters (everything after /?)
Exclude url’s that are in the domain but fall into a specific subdomain or path (like example.com/blog/....)
I am sure there are other ideas as well :)

**Comment by ferBonnin** [comment]
triaged with the team. Agreed to add this to our backlog. Some additional notes 
* we should capture the command line (both allow and reject) somewhere so users know how these results were found.
* marking this as help wanted in case someone wants to take this on sooner

**Comment by brocktaylor7** [comment]
The implementation for this will need to happen on the Accessibility Insights Service as the crawling logic and inputs all pass through to a library we consume from that repo. I've filed a feature request on that repo to give broader visibility. You can find the new issue here: https://github.com/microsoft/accessibility-insights-service/issues/2208
