### ISSUE TITLE
ADO extension not found

### ISSUE THREAD

**Issue by 0GiS0** [microsoft/accessibility-insights-action#1057]
## Describe the bug

I tried to install the ADO extension but It's not found in the marketplace.

**To Reproduce**

1. Go to [https://github.com/microsoft/accessibility-insights-action/blob/main/docs/ado-extension-usage.md](https://github.com/microsoft/accessibility-insights-action/blob/main/docs/ado-extension-usage.md)
2. Click on [https://marketplace.visualstudio.com/items?itemName=accessibility-insights.prod](https://marketplace.visualstudio.com/items?itemName=accessibility-insights.prod)
3. See error

## Expected behavior

You should see the extension and installed in that page

## Screenshots

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/175379/154520081-287eb850-1801-45a6-89b5-417c554b5dad.png">

**Comment by ThanyaLeif** [comment]
We apologize for the inconvenience, the extension is currently in the beta stage. We will contact you in short with installation guidance.

**Comment by ThanyaLeif** [comment]
The user was contacted with further information about the ADO extension and the issue was solved.
