### ISSUE TITLE
Docs/help text for scanUrlRelativePath suggest bogus "//" value for Windows agents

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-action#1067]
## Describe the bug

Our documentation/help text/input descriptions for Scan URL Relative Path inputs consistently suggests using a value of `//` on Windows, but this is incorrect. This input is used as a relative URL path passed to `url.resolve`; its behavior is not OS-specific, and on all systems, passing `//` will actually have the effect of forcing the system to use the totally bogus `baseUrl` of "`http://`".

We should:

* Correct all references to this in task/action definitions and usage docs
* Ensure that if the user *does* pass `//`, they get a reasonable error message
* Update the unit tests for the `scan-url-resolver` to pin the behavior of this (and other incorrect use cases that a confused user might feasibly include, like paths with backslashes or absolute paths or query parameters or empty strings)

**To Reproduce**
1. Try following the docs and passing `//` to the input in a `siteDir`-based configuration
2. Observe that it tries to scan `http://`

## CodePen repro example

n/a

## Expected behavior

Our documentation shouldn't suggest the bogus parameter, and if the user tries passing it anyway, the error should be actionable

## Screenshots

n/a

## Context (please complete the following information)

- OS Name & Version: windows-2016 standard agent
- AI-Action Version & Environment: Azure DevOps extension v1.1.1 production
- Browser Version: n/a
- Target Page: n/a

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

## Additional context

n/a

**Comment by lisli1** [comment]
In #1231, we removed the references to using `//` on Windows in gh-action-usage.md

**Comment by katydecorah** [comment]
I went to pick this up and I think it has been resolved 😅 `scanUrlRelativePath` was renamed to `staticSiteUrlRelativePath` and the documentation for that parameter no longer mentions the `//` on Windows.

**Comment by katydecorah** [comment]
This was resolved.
