### ISSUE TITLE
Missing reference docs for task/action inputs

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-action#1069]
## Describe the bug

Right now, there are several inputs for both the ADO task and action which our usage docs never mention (eg, we never document how a user should decide whether or not to specify `chromePath`). We should go through every input and ensure that each of them has at least *some* usage documentation.

**To Reproduce**

n/a

## CodePen repro example

n/a

## Expected behavior

All inputs should be documented.

## Screenshots

n/a

## Context (please complete the following information)

- OS Name & Version: n/a
- AI-Action Version & Environment: v1.1.1 production
- Browser Version: n/a
- Target Page: n/a

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

## Additional context

n/a

**Comment by ThanyaLeif** [comment]
Documentation was updated in PR #1130.
