### ISSUE TITLE
Reduce onboarding complexity by replacing dependency on yarn

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/accessibility-insights-action#1109]
## Describe the bug

This issue reflects some conversation on our support thread and with @dbjorge 

`yarn` is a an undocumented dependency of the Azure DevOps extension task. This is because the task installs its dependencies at runtime using the `yarn` package manager. While Microsoft hosted pool agents include `yarn` by default, some build environments don't have `yarn` installed. This increases onboarding complexity because users need to debug the error and add `yarn` to their pipeline themselves.

Users also need `node >= 10.x`. This is because the puppeteer install script (and perhaps others) run 'node install.js'. The ADO task execution handler runs node10 but installing node6 for example, may prefix the PATH and fail - puppeteer uses async syntax which isn't supported until 10.x. 

### Constraints

We install dependencies at runtime instead of pre-building them for a few reasons:
- VSIX files have a maximum size limit of 50 MB. [The documentation](https://docs.microsoft.com/en-us/azure/devops/extend/publish/overview?view=azure-devops#check-package-size) suggests a mitigation: "Fetch things at runtime or during install time rather than providing it within the package."
- Some deps like `puppeteer` have different postinstall steps based on the OS platform; we might need to create and maintain several bundles

### Current approach

We maintain a `yarn.lock` file that represents the required runtime dependencies. We assume `yarn` exists on the build agent and [invoke `yarn install`](https://github.com/microsoft/accessibility-insights-action/blob/main/packages/ado-extension/src/install-runtime-dependencies.ts) towards the beginning of task execution.

### Possible improvements

- [x] #1123
- [ADO documentation](https://docs.microsoft.com/en-us/azure/devops/extend/publish/overview?view=azure-devops#check-package-size) also suggests "Consider using the tool installer lib to pull tool dependencies at runtime. Using the lib offers benefits where the tool is cached by version so for private agents, it won't get downloaded every build. We made it a lib so it can be used outside of tool installer tasks. But, the task won't work in disconnected scenarios (no internet), which should be in the description / docs for the task." See if leveraging the tool installer lib ([sample here](https://github.com/microsoft/azure-pipelines-tool-lib/blob/master/sample.ts)) would help us.
- Switch from `yarn` to `npm` for runtime-installation since `npm` will exist more often in `node` environments than `yarn` will. We don't use `npm` for our own local development yet because of issues like https://github.com/npm/cli/issues/4232#issuecomment-1034240038 - we need override behavior. If we take this approach, Dan suggests converting our `yarn.lock` file to `package-lock.json` using something like https://github.com/imsnif/synp.
- ...others?

**Comment by asksep** [comment]
We split this into 2 issues to track adding documentation as an initial 'go-do' task [Add the yarn tooling requirement to our documentation (easy to do) #1123](https://github.com/microsoft/accessibility-insights-action/issues/1123).

Second, we flagged this original thread as "await community interest" to track if this yarn-dependency is prevalent across other teams trying to onboard.

**Comment by dbjorge** [comment]
I'm moving this from "await community interest" back to "ready for triage" based on several recent support threads that were challenging to debug which occurred because of this issue. Besides increasing the amount of steps required to onboard, it makes it easy to introduce very confusing issues - for example, mis-ordering a yarn install vs node install step can cause different parts of the task to end up using different node versions in ways that aren't obvious.

**Comment by katydecorah** [comment]
To add another observation, `windows-latest` and `ubuntu-latest` are now on Node v18. This means we have also seen more users needing to add the NodeTool step to target Node 16. Since Node often comes packaged with npm, I'm curious if the option to switch from yarn to node would help reduce onboarding complexity.
