### ISSUE TITLE
Does this Private Extension work if we move ADO to Customer Tenant

### ISSUE THREAD

**Issue by shubhammicrosoft1** [microsoft/accessibility-insights-action#1190]
Hi Team
This is listed as a Private Extension in Devops Marketplace , can the ADO continue to use it if that moves from the MS tenant to Customer tenant
If they are not available once ADO moves in the customer tenant , are there any alternative versions available for customers can continue to use them

**Comment by ThanyaLeif** [comment]
Hi @shubhammicrosoft1 
ADO Extension is exclusive for MS internal, which means if someone moves from MS tenant to Customer tenant the extension will stop working.
But we offer the option of GH Action for external users, the Accessibility Insights Action helps integrate automated accessibility tests in your GitHub workflow, you can find more information about our product at this link: https://github.com/microsoft/accessibility-insights-action
