### ISSUE TITLE
Emoji in ADO UploadSummary are shown as string values

### ISSUE THREAD

**Issue by katydecorah** [microsoft/accessibility-insights-action#1263]
## Describe the bug

When the ADO extension completes a job and finds no issues, the summary contains emoji that are not being converted to images and remain as strings: `:white_check_mark:` and `:point_right:`.

**To Reproduce**

1. Visit a recent pipeline, such as [docs](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=36274&view=ms.vss-build-web.run-extensions-tab)
2. Review the summary to see that `:white_check_mark:` is a string and not show as :white_check_mark: and `:point_right:` is a strong and is not shown as 👉 

## CodePen repro example

n/a

## Expected behavior

The emoji should be an image, not a string. However, since the emoji are decorative, removing them may be the ideal option.

## Screenshots

![Screenshot of the ADO summary where text shows emoji as string: :white_check_mark: No failures detected
 :point_right: Next step: Manually assess keyboard accessibility with Accessibility Insights Tab Stops)](https://user-images.githubusercontent.com/2180540/183943010-8ced70ce-184f-43c4-8d92-49d76f651b9a.png)

## Context (please complete the following information)

- OS Name & Version: 
- AI-Action Version & Environment: 
- Browser Version: 
- Target Page: 

## Are you willing to submit a PR?

Yes

## Did you search for similar existing issues?

Yes

**Comment by dbjorge** [comment]
Discussed in triage today, we'll attempt to replace the `:emojiname:` style emojis with unicode characters and if that doesn't resolve it, just remove them
