### ISSUE TITLE
Abstract error message thrown when crawler encounters browser errors

### ISSUE THREAD

**Issue by katydecorah** [microsoft/accessibility-insights-action#1315]
## Describe the bug

When the crawler encounters a browser error, it will often throw the following error:

```
[error][Exception]ErrorWithCause: An error occurred while scanning website page
....
caused by: TypeError: Cannot read properties of undefined (reading 'baseUrl')
    at Scanner.getCombinedReportParameters (/home/vsts/work/_tasks/accessibility-insights_4811a442-2fd3-5aa8-ba1a-14cb7e24c113/3.0.0/index.js:191027:60)
    at Scanner.<anonymous> (/home/vsts/work/_tasks/accessibility-insights_4811a442-2fd3-5aa8-ba1a-14cb7e24c113/3.0.0/index.js:191005:55)
    at Generator.next (<anonymous>)
    at fulfilled (/home/vsts/work/_tasks/accessibility-insights_4811a442-2fd3-5aa8-ba1a-14cb7e24c113/3.0.0/index.js:190928:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

I believe this is happening because the `combinedScanResult` in `scanner.ts` returns an `errors` array which does not get evaluated and elevated to the logger. As a result, the `getCombinedReportParameters` attempts to create the report metadata, but because it doesn't exist, it fails when it attempts to reach the `baseUrl`. The error message thrown is abstracted from the actual problem - the crawler isn't getting a page response.

**To Reproduce**

I created an [example build](https://dev.azure.com/accessibility-insights-private/Accessibility%20Insights%20(private)/_build/results?buildId=37895&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=7384d774-f7ca-599c-ee57-ab2c05be9247&s=96ac2280-8cb4-5df5-99de-dd2da759617d)

## CodePen repro example

n/a

## Expected behavior

The scanner evaluates the `errors` array and called `this.logger.error()` for each error. This will return an improved error message from the scanner: `Unable to get a page response from the browser` 

Prior art from the service:
- [handles errors array](https://github.com/microsoft/accessibility-insights-service/blob/171bc5eff976890d54cc6cb53497ea1acbb0a389/packages/cli/src/runner/crawler-command-runner.ts#L43-L52)
- [test case with browser error](https://github.com/microsoft/accessibility-insights-service/blob/791716fc36fa2d8c68a2946cfb4ba05a38e9a128/packages/scanner-global-library/src/page-navigator.spec.ts#L298-L323)

## Context (please complete the following information)

- OS Name & Version: 
- AI-Action Version & Environment: ADO@v3
- Browser Version: 
- Target Page: 

## Are you willing to submit a PR?

Yes

## Additional context

@jlperkins and I debugged two different pipelines with this error over the past week.

**Comment by jlperkins** [comment]
Yep, would be good to surface these errors. Thanks for creating the issue, Katy
