### ISSUE TITLE
Improve Release pipeline support

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-action#1602]
## Is your feature request related to a problem? Please describe.

Today, if a user tries to add the task to a release pipeline, they get a confusing error message when the task attempts to upload the results artifact. We have [an internal FAQ on how to avoid the error](https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/accessibility-insights/faq#ado-release-pipeline), but it's not thrilling that the error message when you try it naively is unactionable.

## Describe the desired outcome

Ideally, I think we'd detect that we're running in a release and automatically switch to using `##vso[task.uploadfile]` rather than uploading an artifact

## Describe alternatives you've considered

If there are issues with doing uploadfile, a smaller improvement would be to automatically detect that we're in a release and early-exit with a more actionable error message (similar to the FAQ, or maybe pointing to the FAQ) explaining what the user needs to configure.

## Additional context

n/a

**Comment by dbjorge** [comment]
Had another customer hit this today

**Comment by DaveTryon** [comment]
Unfortunately, this is out of scope given our current priorities.

Thanks for using Accessibility Insights!
