### ISSUE TITLE
[Feature request]: Normalize GUIDs in baselines

### ISSUE THREAD

**Issue by DaveTryon** [microsoft/accessibility-insights-action#1802]
## Is your feature request related to a problem? Please describe.
(From an internal StackOverflow request): 

I setup the ADO extension for accessibility testing in our build pipeline.

I need to skip 4 known issues with baseline setup.

What has happened, 3 of the 4 are detecting as new items comparing to the baseline b/c of a dynamic generated html tag .
```
aria-describedby="6fd7dfac-3b24-4fae-91a5-891726792012 6fd7dfac-3b24-4fae-91a5-891726792013"
```
The context of this tag is randomly generated every time. How can I exclude this html tag in the baseline config?

The general tactic here is to redact all GUIDs as # hashes e.g.

```
aria-describedby="########-####-####-####-############ ########-####-####-####-############"
```
instead of
```
aria-describedby="6fd7dfac-3b24-4fae-91a5-891726792012 6fd7dfac-3b24-4fae-91a5-891726792013"
```
or some other character you find fit, maybe * stars / asterisks? - for both actual results and the hardwired (expected) HTML snapshot.

## Describe the desired outcome

Can we provide a mechanism that allows us to normalize GUIDs in baselines and in comparisons? The most generalized version might be to support a `baseline-substitutions.json` file. The pipeline owner provides this json file, then the baseline code simply applies each substitution in the order they appear in the collection. That allows the pipeline owner to customize to their needs while keeping the core code as simple as possible.

**Comment by lesongjia** [comment]
Is there a way to auto detect the Guid in the html snapshot and either remove the tag or mask them as ########-####-####-####-############

This way, the generated baseline config can be directly used. It is more convenient for partners

**Comment by DaveTryon** [comment]
> Is there a way to auto detect the Guid in the html snapshot and either remove the attribute or mask them as ########-####-####-####-############
> 
> This way, the generated baseline config can be directly used. It is more convenient for partners

@lesongjia, we thought about this and decided that we explicitly don't want to take the route of baking substitutions into the code because of the following long-term support issues:
- **Velocity** : If a team wants a new substitution, it opens a loop of feature request/code change/deployment, all of which might take some time and might require multiple iterations. Having this in a config file controlled by the team allows them to iterate on a much faster loop.
- **Compatibility** : If we've added substitutions, then each new substitution increases the risk of unintentionally impacting the baseline files created by a previous version of the tool.
- **Debuggability** : If a problem occurs, it's much easier to be able to have everything in a single repo than to have it spread across multiple repos owned by multiple teams.

**Comment by DaveTryon** [comment]
The current plan of record is this:
- Add a config file that provides regex strings and their substitutions. For any given snippet, we will repeatedly run the first regex and substitution until it no longer produces a match or until we hit an upper bound (to avoid infinite expansion), then move to the next pair, then the next, until we run out of pairs.
- Write the regex/substitution pairs to the log file as part of running the tool. This is to provide the debugging information in one place in case people need to troubleshoot.
- Add a list of common substitutions to the documentation, so teams don't need to reinvent expressions that have already been figured out. If a team figures out a regex that they'd like to share, they're free to open a PR to add it to the list

**Comment by Shinigami-k** [comment]
Adding on to the feature request, is it possible to add the regex for cssSelector as well? The baseline usually looks like following:

{
      cssSelector: 'button[id^="L1Content_"]', //I have added startsWith char to id
      htmlSnippet: '<button aria-expanded="false" aria-haspopup="true" aria-setsize="3" aria-posinset="3" class="root-165">',
      rule: 'aria-allowed-attr',
      urls: [],
},

Now, I simply want that all the cssSelector that match id pattern for button should get a pass for rule 'aria-allowed-attr'. This may prevent the need for adding htmlSnippet altogether. Additionally, if htmlSnippet is provided, its attributes will be checked against actual snippet. What I mean is htmlSnippet in baseline need not be exact match with the actual html snippet and matching is done based on provided attributes. Does something like this exist? If not, can it be added

**Comment by DaveTryon** [comment]
@Shinigami-k, we plan to apply the regex to the entire fingerprint, not just to the selector. The fingerprint includes the rule, the snipped, the cssSelector, and the xPathSelector. That should give you enough flexibility to do whatever you need it to to. We absolutely do _not_ want to bake any hardcoded assumptions into the core baseline code, since what works for one team might break another team.

**Comment by DaveTryon** [comment]
@Shinigami-k, I think I misspoke before. We don't support xPathSelector at this time, and we have no current plans to add it. Sorry for any confusion.
