### ISSUE TITLE
Supporting Single Page App for crawler with # in the inputUrl

### ISSUE THREAD

**Issue by lesongjia** [microsoft/accessibility-insights-action#1870]
## Is your feature request related to a problem? Please describe.
SO post: https://stackoverflow.microsoft.com/questions/369395
Related Issue: https://github.com/microsoft/accessibility-insights-action/issues/1809

## Describe the desired outcome
Crawler should work with SPA, this is a very common use case for Azure Portal Extension.

**Comment by DaveTryon** [comment]
Hi, @lesongjia! We definitely want to enable this scenario. We've created an internal feature for this in our backlog, and will implement it as soon as we are able to do so. I'm closing this, since we try to avoid having the requests in 2 places.

Thanks for using Accessibility Insights!
