### ISSUE TITLE
Rename NOTICES.txt to NOTICE.txt

### ISSUE THREAD

**Issue by pownkel** [microsoft/accessibility-insights-action#236]
Our open-source guidance asks for our third-party notices to be in a file called NOTICE.txt. Ours is called NOTICES.txt due to a yarn bug that causes any yarn command to crash when a large file named NOTICE.* is present (see the note on #233). The file should probably be renamed when yarn releases a fix.

**Comment by ferBonnin** [comment]
per conversation with Peter, the yarn bug seems to be fixed so we should address this

**Comment by DaveTryon** [comment]
It appears that we're still blocked by the bug in Yarn. @ferBonnin, I'm moving this to blocked state since it's not something that we can directly control without trying to diagnose and fix the bug in yarn).

**Comment by ferBonnin** [comment]
@DaveTryon can you please link here the active yarn bug?

**Comment by AhmedAbdoOrtiga** [comment]
The file name now is NOTICE.html and it's included only in the release bits
