### ISSUE TITLE
Action adds its check to the wrong workflow if it is re-run

### ISSUE THREAD

**Issue by dbjorge** [microsoft/accessibility-insights-action#631]
In https://github.com/microsoft/accessibility-insights-action/pull/628, I initially created the PR from a fork, and in our self-validation job, the action failed to add our custom check due to #629 

I re-created the action from an upstream branch and selected "Re-run all jobs" from the checks UI, and the resulting re-run was able to add the custom check successfully as expected (since `GITHUB_TOKEN` has the appropriate checks write permissions when run from a non-forked repo), but the check was added to the first workflow instead of the rerun workflow like it should have been. This results in the corresponding PR (#628) showing "all checks succeeded" even though the accessibility checks include failures.

The action should instead detect which workflow it is running within when it is creating the checks (or, with the #629 fix, the workflow that the build artifact was added from) and add the results there.

**Comment by karanbirsingh** [comment]
I wonder if this is related to https://github.community/t/specify-check-suite-when-creating-a-checkrun/118380 - the [create-check-run endpoint](https://docs.github.com/en/rest/reference/checks#create-a-check-run) doesn't offer a suite ID option, so the linking is managed by GitHub:

> annotations generated in a Github action during a step executed in the “pull request” event, end up in the “workflow” for the "push’ event. Through hoops, it is possible to find the check run ID during a Github Action ... However, there is no way to specify the Check Suite ID when creating a new check run (its ignored in the request) and neither there seems to be any dedicated endpoint for creating check runs for a particular check suite.

**Comment by ferBonnin** [comment]
changing to needs investigation per conversation with @peterdur

**Comment by asksep** [comment]
The check-run has been removed, therefor the Accessibility Insights Team is marking this bug as obsolete/closed
