### ISSUE TITLE
Angle brackets in rule description not escaped in scan result markdown

### ISSUE THREAD

**Issue by peterdur** [microsoft/accessibility-insights-action#674]
Visit https://github.com/asksep/test-ai-action/runs/2657373953?check_suite_focus=true

Note the third failed instance on this page reads

1 × image-alt: Ensures <img> elements have alternate text or a role of none or presentation

It should read

1 × image-alt: Ensures \<img\> elements have alternate text or a role of none or presentation

Viewing the page source finds a linked image between Ensures and elements:

`1 × image-alt</strong>:  Ensures <a target="_blank" rel="noopener noreferrer" href=""><img style="max-width:100%;"></a> elements` 

Running AI-Web on this page, entertainingly enough, spots an **image-alt** violation (the generated image has no alternate text or role) and a **link-name** violation (images in markdown are links to the image file). The empty linked image also creates an invisible tab stop.

Markdown generation should be reviewed to identify any other data or characters that need to be escaped.

**Comment by karanbirsingh** [comment]
This has been released in v2.2.0

**Comment by peterdur** [comment]
Verified corrected behavior at https://github.com/peterdur/test-ai-action/pull/3
