### ISSUE TITLE
index.js files are not checked in from a build machine

### ISSUE THREAD

**Issue by karanbirsingh** [microsoft/accessibility-insights-action#717]
The GitHub action [runs index.js](https://github.com/microsoft/accessibility-insights-action/blob/68ce3f6c55d395de78c5c9107dd7c392dc59434b/action.yml#L65). However, this file is not built & checked in from a build machine. Instead, the file is built on developer machines & checked in via the PR process. Changes in this file are difficult to review because the file is bundled via webpack; unrelated updates in third-party components can show up in the diff.

One approach to solve this problem is to build index.js in a pipeline and push it to a separate "release" repository or branch. Users would reference the "release" repository in consuming pipelines. This repository's source tree would only contain TypeScript files.

**Comment by AhmedAbdoOrtiga** [comment]
This issue was resolved, the index.js is now checked only in the release bits and via a build pipeline not the dev machine anymore
