### ISSUE TITLE
[ADO Extension] E2E tests

### ISSUE THREAD

**Issue by lisli1** [microsoft/accessibility-insights-action#866]
E2E tests were disabled in #844 due to an [issue in webpack](https://github.com/microsoft/azure-pipelines-task-lib/issues/794). When it is resolved, the tests will need to be turned back on.

**Comment by asksep** [comment]
The GitHub Repo token usage is obsolete, therefor the Accessibility Insights team is going to investigate enabling new E2E tests

**Comment by katydecorah** [comment]
I'm moving this backed to blocked. https://github.com/microsoft/azure-pipelines-task-lib updated `azure-pipelines-task-lib/mock-test` with Node 16 but hasn't release yet. This means that the e2e tests run on Node 10 and then fails when it runs the scan package (which requires Node 16).
